export const WORD_CATEGORIES = {
  Animales: [
    "Perro",
    "Gato",
    "León",
    "Tigre",
    "Elefante",
    "Caballo",
    "Vaca",
    "Oveja",
    "Cerdo",
    "Conejo",
    "Mono",
    "Panda",
    "Canguro",
    "Delfín",
    "Tiburón",
    "Pingüino",
    "Jirafa",
    "Cebra",
    "Lobo",
    "Zorro",
    "Águila",
    "Búho",
    "Oso",
    "Rinoceronte",
    "Hipopótamo"
],
 Películas: [
    "Avengers",
    "Frozen",
    "Harry Potter",
    "Los Vengadores",
    "Spider-Man",
    "Toy Story",
    "Star Wars",
    "Jurassic World",
    "El Rey León",
    "The Incredibles",
    "Black Panther",
    "Los Juegos del Hambre",
    "Shrek",
    "Minions",
    "Transformers",
    "La Sirenita",
    "Coco",
    "Moana",
    "Encanto",
    "Avatar",
    "The Batman",
    "Deadpool",
    "It",
    "Soul",
    "Detective Pikachu"
],
Celebridades: [
    "Ariana Grande",
    "Taylor Swift",
    "Beyoncé",
    "Ed Sheeran",
    "Dua Lipa",
    "Billie Eilish",
    "Drake",
    "Bad Bunny",
    "The Weeknd",
    "Kanye West",
    "Rihanna",
    "Shakira",
    "Justin Bieber",
    "Selena Gomez",
    "Bruno Mars",
    "Harry Styles",
    "Lady Gaga",
    "Olivia Rodrigo",
    "Kendall Jenner",
    "Kim Kardashian",
    "Will Smith",
    "Zendaya",
    "Chris Hemsworth",
    "Tom Holland",
    "Emma Watson"
]
,
  Comida: [
    "Pizza",
    "Hamburguesa",
    "Hot Dog",
    "Taco",
    "Pasta",
    "Sushi",
    "Ensalada",
    "Helado",
    "Bistec",
    "Pollo frito",
    "Panqueques",
    "Burrito",
    "Cereal",
    "Chocolate",
    "Galletas",
    "Quesadilla",
    "Nachos",
    "Ramen",
    "Curry",
    "Sandwich",
    "Arepa",
    "Pizza vegetariana",
    "Fruta",
    "Sopa",
    "Papitas fritas"
]
,
  Lugares: [
    "París",
    "Nueva York",
    "Tokio",
    "Londres",
    "Roma",
    "Barcelona",
    "Sídney",
    "Los Ángeles",
    "Dubai",
    "Berlín",
    "Madrid",
    "Ámsterdam",
    "Estambul",
    "San Francisco",
    "Chicago",
    "Singapur",
    "Hong Kong",
    "Río de Janeiro",
    "Moscú",
    "Beijing",
    "Cancún",
    "Playa",
    "Montaña",
    "Desierto",
    "Bosque"
]
,
  Objetos: [
    "Guitarra",
    "Laptop",
    "Bicicleta",
    "Cámara",
    "Reloj",
    "Paraguas",
    "Mochila",
    "Gafas de sol",
    "Audífonos",
    "Libro",
    "Piano",
    "Teléfono",
    "Telescopio",
  ],
  Deportes: [
    "Fútbol",
    "Básquetbol",
    "Tenis",
    "Natación",
    "Boxeo",
    "Golf",
    "Esquí",
    "Surf",
    "Béisbol",
    "Voleibol",
    "Hockey",
    "Ciclismo",
    "Bádminton",
    "Atletismo",
    "Fórmula 1",
    "Karate",
    "Taekwondo",
    "Rugby",
    "Fútbol Americano",
    "Skateboarding",
    "Snowboard",
    "Ping Pong",
    "Gymnastics",
    "Escalada",
    "Remo"
],

  Jugadores: [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Kylian Mbappé",
    "Neymar",
    "Erling Haaland",
    "Kevin De Bruyne",
    "Luka Modrić",
    "Robert Lewandowski",
    "Vinícius Jr",
    "Mohamed Salah",
    "Antoine Griezmann",
    "Harry Kane",
    "Sergio Ramos",
    "Virgil van Dijk",
    "Gianluigi Buffon",
    "Paulo Dybala",
    "Raheem Sterling",
    "Karim Benzema",
    "Marc-André ter Stegen",
    "Joshua Kimmich",
    "Romelu Lukaku",
    "Jadon Sancho",
    "Phil Foden",
    "Sadio Mané",
    "Marco Reus"
]
,

  Superheroes: [
    "Spiderman",
    "Capitan America",
    "Iron Man",
    "Hulk",
    "Thor",
    "Black Widow",
    "Black Panther",
    "Hawkeye",
    "Batman",
    "Flash",
    "Superman",
    "Wonder Woman",
    "Green Lantern",
    "Thanos",
    "Ant-Man",
    "Scarlet Witch",
    "Aquaman",
  ],    
  ClashRoyale: [
    "Mosquetera",
    "Mini P.E.K.K.A",
    "Gólem",
    "Montapuercos",
    "Dragon Infernal",
    "Barril de Duendes",
    "Princesa",
    "Ejército de Esqueletos",
    "Esbirros",
    "Horda de Esbirros",
    "Bebé Dragón",
    "Cementerio",
    "Torre Infernal",
    "Torre Tesla",
    "Bruja",
    "Mago",
    "Mago de Hielo",
    "Gigante",
    "Príncipe",
    "Caballero",
    "P.E.K.K.A",
    "Guardias Reales",
    "Duendes",
    "Bebé Dragón",
    "Flechas",
    "Bola de Fuego",
    "Rayo",
    "Tronco",
    "Esqueleto Gigante",
    "Bruja Nocturna",
    "Murciélagos",
    "Golem de Hielo",
    "Megaesbirro",
    "Mago Eléctrico",
    "Cañón",
    "Mortero",
    "Sabueso de Lava",
    "Globo Bombástico",
    "Guardias",
    "Curandera",
    "Dragón Eléctrico",
    "Bárbaros",
    "Recolector de Elixir",
    "Tesla"
  ],
  Kings: [
    "Aldahir Rojas",
    "Alfonso Linares",
    "Arath JG",
    "Arturo Barradas",
    "Christian Mijangos",
    "Eduardo Zendejas",
    "Iker Ruiz",
    "Luis Carlos",
    "Mario OZ",
    "Alejandrez",
    "Omar Alexandro",
    "Omar Vazquez",
    "Paulo",
    "Rafael",
    "Ricardo Carreto",
    "Said Cisneros",
    "Victor Balcazar",
  ]
} as const;

export const CATEGORY_LABELS: Record<string, string> = {
  Animales: "Animales",
  Películas: "Películas",
  Celebridades: "Celebridades",
  Comida: "Comida",
  Lugares: "Lugares",
  Objetos: "Objetos",
  Deportes: "Deportes",
  Jugadores: "Futbolistas", 
  Superheroes: "Superhéroes", 
  ClashRoyale: "Clash Royale", 
  Kings: "Kings"
} as const;

export const GAME_MODES = [
  { value: "classic", label: "Clásico (1 Impostor)" },
  { value: "double", label: "Doble Agente (2 Impostores)" },
  { value: "confusion", label: "Confusión (1 Impostor)" },
  { value: "silence", label: "Silence Mode (No Talking)" },
  { value: "secret", label: "Secret Roles (Detective/Clown)" },
  { value: "team", label: "Team vs Team" },
] as const

export const DISCUSSION_TIMES = [
  { value: 180, label: "3 minutos" },
  { value: 300, label: "5 minutos" },
  { value: 420, label: "7 minutos" },
  { value: 600, label: "10 minutos" },
] as const

export const MIN_PLAYERS = 3
export const TURN_TIME = 30 
export const VOTING_TIME = 60
