export const WORD_CATEGORIES = {
  Animales: [
    "León",
    "Elefante",
    "Delfín",
    "Pingüino",
    "Koala",
    "Tigre",
    "Jirafa",
    "Pulpo",
    "Canguro",
    "Panda",
    "Cebra",
    "Flamenco",
    "Guepardo",
    "Búho",
  ],
  Películas: [
    "Titanic",
    "Avatar",
    "El Origen",
    "Tiburón",
    "Gladiador",
    "Forrest Gump",
    "Matrix",
    "Parque Jurásico",
    "Star Wars",
    "El Padrino",
    "Rocky",
  ],
  Comida: [
    "Pizza",
    "Sushi",
    "Hamburguesa",
    "Taco",
    "Pasta",
    "Ramen",
    "Curry",
    "Sándwich",
    "Ensalada",
    "Helado",
    "Panqueques",
    "Bistec",
    "Burrito",
  ],
  Lugares: [
    "París",
    "Tokio",
    "Playa",
    "Montaña",
    "Desierto",
    "Bosque",
    "Biblioteca",
    "Museo",
    "Aeropuerto",
    "Estadio",
    "Hospital",
    "Escuela",
    "Restaurante",
  ],
  Objetos: [
    "Guitarra",
    "Laptop",
    "Bicicleta",
    "Cámara",
    "Reloj",
    "Paraguas",
    "Mochila",
    "Gafas de sol",
    "Audífonos",
    "Libro",
    "Piano",
    "Teléfono",
    "Telescopio",
  ],
  Deportes: [
    "Fútbol",
    "Básquetbol",
    "Tenis",
    "Natación",
    "Boxeo",
    "Golf",
    "Esquí",
    "Surf",
    "Béisbol",
    "Voleibol",
    "Hockey",
    "Ciclismo",
    "Bádminton",
  ],

  Jugadores: [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Kylian Mbappé",
    "Neymar",
    "Erling Haaland",
    "Kevin De Bruyne",
    "Luka Modrić",
    "Robert Lewandowski",
    "Vinícius Jr",
    "Mohamed Salah",
    "Antoine Griezmann",
    "Harry Kane",
    "Sergio Ramos",
    "Virgil van Dijk",
    "Gianluigi Buffon",
  ],

  Superheroes: [
    "Spiderman",
    "Capitan America",
    "Iron Man",
    "Hulk",
    "Thor",
    "Black Widow",
    "Black Panther",
    "Hawkeye",
    "Batman",
    "Flash",
    "Superman",
    "Wonder Woman",
    "Green Lantern",
    "Thanos",
    "Ant-Man",
    "Scarlet Witch",
    "Aquaman",
  ],    
  ClashRoyale: [
    "Mosquetera",
    "Mini P.E.K.K.A",
    "Gólem",
    "Montapuercos",
    "Dragon Infernal",
    "Barril de Duendes",
    "Princesa",
    "Ejército de Esqueletos",
    "Esbirros",
    "Horda de Esbirros",
    "Bebé Dragón",
    "Cementerio",
    "Torre Infernal",
    "Torre Tesla",
    "Bruja",
    "Mago",
    "Mago de Hielo",
    "Gigante",
    "Príncipe",
    "Caballero",
    "P.E.K.K.A",
    "Reclutas Reales",
    "Duendes",
    "Mini Dragón",
    "Flechas",
    "Bola de Fuego",
    "Rayo",
    "Tronco",
    "Esqueleto Gigante",
    "Bruja Nocturna",
    "Murciélagos",
    "Golem de Hielo",
    "Megaesbirro",
    "Mago Eléctrico",
    "Cañón",
    "Mortero",
    "Sabueso de Lava",
    "Globo Bombástico",
    "Guardias",
    "Curandera",
    "Dragón Eléctrico",
    "Bárbaros",
    "Recolector de Elixir",
    "Tesla"
  ]
} as const;



export const GAME_MODES = [
  { value: "classic", label: "Clásico (1 Impostor)" },
  { value: "double", label: "Doble Agente (2 Impostores)" },
  { value: "silence", label: "Silence Mode (No Talking)" },
  { value: "secret", label: "Secret Roles (Detective/Clown)" },
  { value: "team", label: "Team vs Team" },
] as const

export const DISCUSSION_TIMES = [
  { value: 180, label: "3 minutos" },
  { value: 300, label: "5 minutos" },
  { value: 420, label: "7 minutos" },
  { value: 600, label: "10 minutos" },
] as const

export const MIN_PLAYERS = 3
export const TURN_TIME = 30 // seconds per turn
export const VOTING_TIME = 60 // seconds for voting
