export const WORD_CATEGORIES = {
  Animals: [
    "León",
    "Elefante",
    "Delfín",
    "Pingüino",
    "Koala",
    "Tigre",
    "Jirafa",
    "Pulpo",
    "Canguro",
    "Panda",
    "Cebra",
    "Flamenco",
    "Guepardo",
    "Búho",
  ],
  Movies: [
    "Titanic",
    "Avatar",
    "El Origen",
    "Tiburón",
    "Gladiador",
    "Forrest Gump",
    "Matrix",
    "Parque Jurásico",
    "Star Wars",
    "El Padrino",
    "Rocky",
  ],
  Food: [
    "Pizza",
    "Sushi",
    "Hamburguesa",
    "Taco",
    "Pasta",
    "Ramen",
    "Curry",
    "Sándwich",
    "Ensalada",
    "Helado",
    "Panqueques",
    "Bistec",
    "Burrito",
  ],
  Places: [
    "París",
    "Tokio",
    "Playa",
    "Montaña",
    "Desierto",
    "Bosque",
    "Biblioteca",
    "Museo",
    "Aeropuerto",
    "Estadio",
    "Hospital",
    "Escuela",
    "Restaurante",
  ],
  Objects: [
    "Guitarra",
    "Laptop",
    "Bicicleta",
    "Cámara",
    "Reloj",
    "Paraguas",
    "Mochila",
    "Gafas de sol",
    "Audífonos",
    "Libro",
    "Piano",
    "Teléfono",
    "Telescopio",
  ],
  Sports: [
    "Fútbol",
    "Básquetbol",
    "Tenis",
    "Natación",
    "Boxeo",
    "Golf",
    "Esquí",
    "Surf",
    "Béisbol",
    "Voleibol",
    "Hockey",
    "Ciclismo",
    "Bádminton",
  ],

  FootballPlayers: [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Kylian Mbappé",
    "Neymar",
    "Erling Haaland",
    "Kevin De Bruyne",
    "Luka Modrić",
    "Robert Lewandowski",
    "Vinícius Jr",
    "Mohamed Salah",
    "Antoine Griezmann",
    "Harry Kane",
    "Sergio Ramos",
    "Virgil van Dijk",
    "Gianluigi Buffon",
  ],

  Superheros: [
    "Spiderman",
    "Capitan America",
    "Iron Man",
    "Hulk",
    "Thor",
    "Black Widow",
    "Black Panther",
    "Hawkeye",
    "Batman",
    "Flash",
    "Superman",
    "Wonder Woman",
    "Green Lantern",
    "Thanos",
    "Ant-Man",
    "Scarlet Witch",
    "Aquaman",
  ],    
} as const;



export const GAME_MODES = [
  { value: "classic", label: "Classic (1 Impostor)" },
  { value: "double", label: "Double Agent (2 Impostors)" },
  { value: "silence", label: "Silence Mode (No Talking)" },
  { value: "secret", label: "Secret Roles (Detective/Clown)" },
  { value: "team", label: "Team vs Team" },
] as const

export const DISCUSSION_TIMES = [
  { value: 180, label: "3 Minutes" },
  { value: 300, label: "5 Minutes" },
  { value: 420, label: "7 Minutes" },
  { value: 600, label: "10 Minutes" },
] as const

export const MIN_PLAYERS = 3
export const TURN_TIME = 30 // seconds per turn
export const VOTING_TIME = 60 // seconds for voting
