// Stub file for Convex API
// In production, this is auto-generated by `npx convex dev`

import type { FunctionReference } from "convex/server"

// Define the API structure matching our functions
export const api = {
  rooms: {
    createRoom: "rooms:createRoom" as unknown as FunctionReference<
      "mutation",
      "public",
      { hostName: string; sessionId: string },
      { roomId: any; code: string }
    >,
    joinRoom: "rooms:joinRoom" as unknown as FunctionReference<
      "mutation",
      "public",
      { playerName: string; roomCode: string; sessionId: string },
      { roomId: any; playerId?: any }
    >,
    getRoom: "rooms:getRoom" as unknown as FunctionReference<"query", "public", { roomId: any }, any>,
    getRoomByCode: "rooms:getRoomByCode" as unknown as FunctionReference<"query", "public", { code: string }, any>,
    getPlayers: "rooms:getPlayers" as unknown as FunctionReference<"query", "public", { roomId: any }, any[]>,
    toggleReady: "rooms:toggleReady" as unknown as FunctionReference<
      "mutation",
      "public",
      { sessionId: string; roomId: any },
      void
    >,
    updateRoomSettings: "rooms:updateRoomSettings" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string; gameMode?: string; category?: string; discussionTime?: number },
      void
    >,
    canStartGame: "rooms:canStartGame" as unknown as FunctionReference<
      "query",
      "public",
      { roomId: any },
      { canStart: boolean; reason?: string }
    >,
  },
  game: {
    startGame: "game:startGame" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string },
      { word: string; impostorIds: string[] }
    >,
    passTurn: "game:passTurn" as unknown as FunctionReference<"mutation", "public", { roomId: any }, void>,
    callVote: "game:callVote" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string },
      void
    >,
    vote: "game:vote" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string; targetSessionId: string },
      void
    >,
    processResults: "game:processResults" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any },
      { winner: string; eliminatedSessionId: string | null; voteCounts: Record<string, number> }
    >,
    playAgain: "game:playAgain" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string },
      void
    >,
    resetRoom: "game:resetRoom" as unknown as FunctionReference<
      "mutation",
      "public",
      { roomId: any; sessionId: string },
      void
    >,
    getCurrentPlayer: "game:getCurrentPlayer" as unknown as FunctionReference<"query", "public", { roomId: any }, any>,
  },
} as const
