// Stub file for Convex data model types
// In production, this is auto-generated by `npx convex dev`

import type { GenericId } from "convex/values"

export type Id<TableName extends string> = GenericId<TableName>

export type Doc<TableName extends string> = TableName extends "rooms"
  ? {
      _id: Id<"rooms">
      _creationTime: number
      code: string
      hostId: string
      status: "waiting" | "playing" | "voting" | "results"
      currentWord?: string
      category?: string
      impostorIds: string[]
      gameMode: string
      discussionTime: number
      turnOrder: string[]
      currentTurnIndex: number
      turnStartTime?: number
      votingStartTime?: number
      roundNumber: number
    }
  : TableName extends "players"
    ? {
        _id: Id<"players">
        _creationTime: number
        name: string
        roomId: Id<"rooms">
        isHost: boolean
        isReady: boolean
        isEliminated: boolean
        score: number
        secretRole?: string
        votedFor?: string
        sessionId: string
      }
    : never
