// Stub file for Convex server functions
// In production, this is auto-generated by `npx convex dev`

import {
  mutation as convexMutation,
  query as convexQuery,
  internalMutation as convexInternalMutation,
  internalQuery as convexInternalQuery,
} from "convex/server"

export const mutation = convexMutation
export const query = convexQuery
export const internalMutation = convexInternalMutation
export const internalQuery = convexInternalQuery
